version: '3'
services:
  play:
    build: ./docker/play
    ports:
      - "9000:9000"
    volumes:
      - ".:/root/play-docker"
    working_dir: /root/play-docker
    environment:
      - FRONTEND_URL=http://localhost:3000
      - MYSQL_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_URL=jdbc:mysql://mysql:3306/number_sign_db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    entrypoint: bash -c "sbt run"

  react:
    build: ./docker/react
    ports:
      - "3000:3000"
    volumes:
      - "./ui:/root/react-docker"
    working_dir: /root/react-docker
    entrypoint: bash -c "npm start"

  mysql:
    image: mysql:8
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
#    GUIからのアクセスでエラーログが出たため追加
    cap_add:
      - SYS_NICE

  play-test:
    build: ./docker/play
    ports:
      - "9001:9001"
    volumes:
      - ".:/root/play-docker"
    working_dir: /root/play-docker
    environment:
      - FRONTEND_URL=http://localhost:3000
      - MYSQL_DRIVER=com.mysql.cj.jdbc.Driver
      - MYSQL_URL=jdbc:mysql://mysql:3306/number_sign_db_test
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    entrypoint: bash -c "sbt test"
    profiles:
      - extra
