version: '3'
services:
  play:
    build: ./docker/play
    ports:
      - "9000:9000"
    volumes:
      - ".:/root/play-docker"
    working_dir: /root/play-docker
    environment:
      - FRONTEND_URL=http://localhost:3000
    entrypoint: bash -c "sbt run"

  react:
    build: ./docker/react
    ports:
      - "3000:3000"
    volumes:
      - "./ui:/root/react-docker"
    working_dir: /root/react-docker
    entrypoint: bash -c "npm start"

  mysql:
    image: mysql:8
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
